configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/align.smk"
include: "rules/contacts.smk"
include: "rules/junctions-view.smk"
include: "rules/hub.smk"


rule all:
    input: 
        contacts = get_all_outputs