configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/align.smk"
include: "rules/postprocess.smk"


print([row for row in samples.itertuples()])

rule all:
    input: 
        contacts = get_all_outputs